import type { LLMProvider, LLMRequest } from "@opennblm/llm-providers";

export type LearnerLevel = "beginner" | "intermediate" | "advanced";
export interface TeachingInput { question: string; learnerLevel?: LearnerLevel; subject?: string; language?: string; learnerContext?: string; }
export interface TeachingPlan { topic: string; learner_level: LearnerLevel; objective: string; key_concepts: string[]; explanation_steps: string[]; examples: string[]; analogy: string; misconception_risks: string[]; comprehension_check: string; summary: string; }
export interface SegmentInstruction { text: string; emphasis?: string; pauseAfterMs?: number; }
export interface DeliveryPlan { overallTone: string; pace: "slow" | "steady" | "brisk"; emphasis: string[]; pauses: number[]; energy: "calm" | "warm" | "bright"; language: string; speaker: "Ira" | "Aisha" | "Siya" | "Zoya"; vocalizationOpportunities: string[]; segmentInstructions: SegmentInstruction[]; }
export interface TeachingResult { plan: TeachingPlan; delivery: DeliveryPlan; response: string; usedFallback: boolean; attempts: number; }
export interface TeachingSession { id: string; }
export interface TeachingEngine { start(session: TeachingSession): Promise<void>; teach(input: TeachingInput): Promise<TeachingResult>; }

const planSchema = { type: "object", required: ["topic", "learner_level", "objective", "key_concepts", "explanation_steps", "examples", "analogy", "misconception_risks", "comprehension_check", "summary"], properties: { topic: { type: "string" }, learner_level: { enum: ["beginner", "intermediate", "advanced"] }, objective: { type: "string" }, key_concepts: { type: "array", items: { type: "string" } }, explanation_steps: { type: "array", items: { type: "string" } }, examples: { type: "array", items: { type: "string" } }, analogy: { type: "string" }, misconception_risks: { type: "array", items: { type: "string" } }, comprehension_check: { type: "string" }, summary: { type: "string" } } };
const asStrings = (value: unknown): value is string[] => Array.isArray(value) && value.every((item) => typeof item === "string" && item.trim().length > 0);
export function validateTeachingPlan(value: unknown): value is TeachingPlan { if (!value || typeof value !== "object") return false; const plan = value as Record<string, unknown>; return typeof plan.topic === "string" && typeof plan.objective === "string" && typeof plan.analogy === "string" && typeof plan.comprehension_check === "string" && typeof plan.summary === "string" && ["beginner", "intermediate", "advanced"].includes(String(plan.learner_level)) && asStrings(plan.key_concepts) && asStrings(plan.explanation_steps) && asStrings(plan.examples) && asStrings(plan.misconception_risks); }
function fallbackPlan(input: TeachingInput): TeachingPlan { const level = input.learnerLevel ?? "beginner"; return { topic: input.question, learner_level: level, objective: `Build a clear working understanding of ${input.question}.`, key_concepts: [input.question], explanation_steps: [`Start with the plain-language idea behind ${input.question}.`, "Connect the idea to one concrete example.", "Check which part feels least clear before going further."], examples: [`Consider a familiar situation related to ${input.question}.`], analogy: "Think of the idea as a path: first find the entrance, then notice the landmarks, then try walking it yourself.", misconception_risks: ["A simple first explanation may leave out important edge cases."], comprehension_check: `In your own words, what is the central idea of ${input.question}?`, summary: `The first useful step is to form a simple, testable understanding of ${input.question}.` }; }
export function buildDeliveryPlan(plan: TeachingPlan, input: TeachingInput): DeliveryPlan { const tone = plan.learner_level === "beginner" ? "warm and reassuring" : plan.learner_level === "advanced" ? "precise and focused" : "clear and encouraging"; const pace = plan.learner_level === "beginner" ? "steady" : "brisk"; return { overallTone: tone, pace, emphasis: plan.key_concepts.slice(0, 3), pauses: plan.explanation_steps.map((_, index) => index), energy: plan.learner_level === "beginner" ? "calm" : "warm", language: input.language ?? "English", speaker: "Ira", vocalizationOpportunities: [], segmentInstructions: plan.explanation_steps.map((text, index) => ({ text, emphasis: plan.key_concepts[index], pauseAfterMs: 450 })) }; }
export function renderTeachingResponse(plan: TeachingPlan): string { return [plan.objective, ...plan.explanation_steps, plan.examples.length ? `For example: ${plan.examples[0]}` : "", plan.analogy ? `A useful analogy: ${plan.analogy}` : "", plan.comprehension_check ? `Quick check: ${plan.comprehension_check}` : "", `In short: ${plan.summary}`].filter(Boolean).join("\n\n"); }
const planRequest = (input: TeachingInput, correction = false): LLMRequest => ({ model: "configured", temperature: 0.3, responseSchema: planSchema, messages: [{ role: "system", content: `You are opennbLM's teaching planner. Return only a JSON object matching the supplied schema. Teach with clarity, progression, intuition, a small number of examples, and a comprehension check. Avoid unnecessary verbosity. Learner level: ${input.learnerLevel ?? "beginner"}.` }, { role: "user", content: correction ? `The previous plan was invalid. Return a corrected complete plan with every required field and valid arrays. Topic: ${input.question}` : `Create a teaching plan for: ${input.question}` }] });
export function createTeachingEngine(provider: LLMProvider): TeachingEngine { return { async start() {}, async teach(input) { let attempts = 0; let plan: TeachingPlan | undefined; let usedFallback = false; for (let retry = 0; retry < 2; retry += 1) { attempts += 1; try { const candidate = await provider.structured<unknown>(planRequest(input, retry === 1)); if (validateTeachingPlan(candidate)) { plan = candidate; break; } } catch {} } if (!plan) { plan = fallbackPlan(input); usedFallback = true; } const delivery = buildDeliveryPlan(plan, input); return { plan, delivery, response: renderTeachingResponse(plan), usedFallback, attempts }; } }; }
